site_name: Todo App Hackathon
theme:
  name: mkdocs
plugins:
  - search
nav:
  - Technical Documentation:
      - Overview: technical/index.md
  - Business Documentation:
      - Overview: business/index.md
      - Views:
          - Calendar View: business/views/calendar.md
          - Timeline View: business/views/timeline.md
      - Actions:
          - Create Todo: business/actions/create-todo.md
          - Update Todo: business/actions/update-todo.md
          - Delete Todo: business/actions/delete-todo.md
          - Complete Day: business/actions/complete-day.md
  - Tags: tags.md